INSERT INTO `hospital`.`volunteers` (`wid`) VALUES ('1077');
INSERT INTO `hospital`.`volunteers` (`wid`) VALUES ('1033');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES ('1099', 'Steve');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES ('1088', 'Fred');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES ('1077', 'Kate');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES ('1066', 'Dave');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES (’1077’,’Jane');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES (‘1066’,’Jane');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES (‘1055’,’Jane');
INSERT INTO `hospital`.`workers` (`wid`, `name`)  VALUES (‘1044’,’Mike');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES (‘1033’,’Sally');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES (‘1022’,’Bob');
INSERT INTO `hospital`.`workers` (`wid`, `name`) VALUES (‘1011’,’John');
